gui:
  title: "分解菜单"
  size: 54
  slots:
    - 'fffffffff'
    - 'fooooooof'
    - 'fooooooof'
    - 'fooooooof'
    - 'fffffffff'
    - 'ffffbffff'
  items:
    b:
      name: '&c&l点击分解'
      material: ANVIL
      lore:
        - "&c点击分解"
      # 确认状态的ItemStack
      ready:
        name: '&c&l请再点击一次确认分解'
        material: ANVIL
        lore:
          - "&6请再点击一次确认分解..."
    f:
      name: '-'
      material: STAINED_GLASS_PANE
      data: 1
      customModelData: 1001
      lore:
        - '&7边框'
      ready:
        data: 2

message:
  success: "§a分解成功 {1} 件,失败 {2} 件."
  # 分解获得金币提醒，由于设计原因可能会造成刷屏，请酌情开启
  money:
    use: false
    msg: "§6你通过分解获得了§f{1}元§6金币"

# 关闭gui自动分解
autoDecompose: false